### ISSUE TITLE
[FEAT] 우리동네 모임 상세조회 기능 추가

### ISSUE THREAD

**Issue by rinarina0429** [DOSOPT-CDS-APP-TEAM5/Carrot-Server#7]
## 🥕 Desciption

우리동네 모임 상세 조회 기능입니다.
- [GET] /api/clubs/{clubId}

## 🥕 To-do
- [x] API 명세서 작성
- [x] 모임 기능 구현
- [x] 앨범 기능 구현
- [x] 모임과 앨범 연결

## 🥕 ETC
예상 마감 기한: 2023.11.21
